config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #root 'todo#homepage'
  get '/categoria', to: 'todo#categoria'
  #resources :todo
  get '/descripcion', to: 'todo#descripcion'
  root 'todo#index'
  get '/resultado', to: 'todo#resultado'
  get '/homepage', to: 'todo#homepage'
  post 'todo/enlistar', to: 'todo#enlistar', as: 'enlistar_pelicula'
  get '/lista', to: 'todo#lista'
  delete 'eliminar_pelicula_lista/:id', to: 'todo#eliminar_pelicula_lista', as: 'eliminar_pelicula_lista'
  #root 'todo#homepage'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/todo_controller.rb
class TodoController < ApplicationController
  
  include Kaminari::PageScopeMethods
  before_action :comun
  before_action :require_login, only: [:lista]
  require 'json'
  require 'rest-client'

  def categoria
    id_genero = params[:id_gen]
    api_key = '7752de1a342e0930da1c72487148b06b'
    @link_img = 'https://image.tmdb.org/t/p/w500'
  
    # Inicializamos un array vacío para almacenar las películas
    @movie_details = []
  
    page_number = 1
    max_pages = 10
  
    while page_number <= max_pages
      url = URI.parse("https://api.themoviedb.org/3/discover/movie?api_key=#{api_key}&language=es-ES&with_genres=#{id_genero}&page=#{page_number}")
  
      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true if url.scheme == 'https'
  
      request = Net::HTTP::Get.new(url.request_uri)
      response = http.request(request)
  
      if response.code == '200'
        movies = JSON.parse(response.body)['results']
        break if movies.empty? # Si no hay más resultados, salimos del bucle
        @movie_details.concat(movies)
      else
        @error_message = "Error: #{response.code}"
        break
      end
  
      page_number += 1
    end
  
    # Paginamos los resultados
    @movie_details = Kaminari.paginate_array(@movie_details).page(params[:page]).per(20)
  end
  def homepage
  end
  def descripcion
    api_key = '7752de1a342e0930da1c72487148b06b'
    movie_id = params[:parametro]
    @link_img = 'https://image.tmdb.org/t/p/w500'
    
    # Obtener información de la película
    url = URI.parse("https://api.themoviedb.org/3/movie/#{movie_id}?api_key=#{api_key}&language=es-ES")
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true if url.scheme == 'https'
    request = Net::HTTP::Get.new(url.request_uri)
    response = http.request(request)
    
    if response.code == '200'
      @info = JSON.parse(response.body)
    else
      @error_message = "Error: #{response.code}"
    end
    
    # Obtener información de los videos
    url_img = URI.parse("https://api.themoviedb.org/3/movie/#{movie_id}/videos?api_key=#{api_key}")
    http = Net::HTTP.new(url_img.host, url_img.port)
    http.use_ssl = true if url_img.scheme == 'https'
    request = Net::HTTP::Get.new(url_img.request_uri)
    response = http.request(request)
    
    if response.code == '200'
      @info_videos = response.body  # No se necesita parsear, ya es un string JSON
    else
      @error_message = "Error: #{response.code}"
    end
    


    if user_signed_in?
      @esta_en_lista = current_user.listums.exists?(pelicula: movie_id)
    else
      @esta_en_lista = false
      # O muestra un mensaje de error, según lo que quieras hacer.
    end
    
  end
  


  def index
    api_key = '7752de1a342e0930da1c72487148b06b'
    url = URI.parse("https://api.themoviedb.org/3/movie/top_rated?api_key=#{api_key}")
    @link_img='https://image.tmdb.org/t/p/w500'
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true if url.scheme == 'https'
    request = Net::HTTP::Get.new(url.request_uri)
    response = http.request(request)
  
    if response.code == '200'
      movies = JSON.parse(response.body)['results']
      @nuevas = Kaminari.paginate_array(movies).page(params[:page]).per(10) # Pagina los resultados, 10 por página
    else
      @error_message = "Error: #{response.code}"
    end
  end
  

  
  

  def resultado
    api_key = '7752de1a342e0930da1c72487148b06b'
    @link_img = 'https://image.tmdb.org/t/p/w500'
    query_i = params[:query]
    peli = query_i.to_s.gsub(/\s/, '%20')
  
    url = URI.parse("https://api.themoviedb.org/3/search/movie?api_key=#{api_key}&query=#{peli}&include_adult=true&language=es-ES&page=1")
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true if url.scheme == 'https'
    request = Net::HTTP::Get.new(url.request_uri)
    response = http.request(request)
  
    if response.code == '200'
      @info = JSON.parse(response.body)['results']
    else
      @error_message = "Error: #{response.code}"
    end
  
    respond_to do |format|
      format.html { render 'resultado' } # Renderizar la vista HTML
      format.js   # Renderizar la vista JS (si se usa AJAX)
    end
  end
  

  def enlistar
    user_id = params[:user_id]
    pelicula_id = params[:pelicula]
    accion = params[:accion] # Nuevo parámetro para indicar si se va a enlistar o quitar
  
    if accion == 'quitar'
      # Código para quitar la película de la lista
      lista = Listum.find_by(user_id: user_id, pelicula: pelicula_id)
      if lista
        lista.destroy
        flash[:success] = "Película quitada de la lista."
      else
        flash[:error] = "La película no estaba en la lista."
      end
    elsif accion == 'enlistar'
      # Código para enlistar la película
      @lista = Listum.new(user_id: user_id, pelicula: pelicula_id)
  
      if @lista.save
        flash[:success] = "Película enlistada exitosamente."
      else
        flash[:error] = "No se pudo enlistar la película."
      end
    end
  
    redirect_to root_path
  end
  
  

  def lista
    require_login
  
    api_key = '7752de1a342e0930da1c72487148b06b'
    @link_img = 'https://image.tmdb.org/t/p/w500'

    
    @info = []
  
    @listas = current_user.listums # Obtener las listas asociadas al usuario actual
  
    @listas.each do |lista|
      movie_id = lista.pelicula
  
      url = URI.parse("https://api.themoviedb.org/3/movie/#{movie_id}?api_key=#{api_key}&language=es-ES")
      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true if url.scheme == 'https'
      request = Net::HTTP::Get.new(url.request_uri)
      response = http.request(request)
  
      if response.code == '200'
        @info << JSON.parse(response.body)
      else
        @error_message = "Error: #{response.code}"
      end
    end
  end
  
  def require_login
    unless current_user
      redirect_to new_user_session_path, notice: 'Por favor inicia sesión para acceder a esta página.'
    end

    query_i = params[:query]
    peli=query_i.to_s.gsub(/\s/, '%20')
  
    # Obtener información de la película
    url = URI.parse("https://api.themoviedb.org/3/search/movie?api_key=#{api_key}&query=#{peli}&include_adult=true&language=es-ES&page=1")
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true if url.scheme == 'https'
    request = Net::HTTP::Get.new(url.request_uri)
    response = http.request(request)
    
    if response.code == '200'
      @info = JSON.parse(response.body)['results']
    else
      @error_message = "Error: #{response.code}"
    end


  end

  def eliminar_pelicula_lista
    require_login
  
    pelicula_id = params[:id]
  
    # Encuentra y elimina la lista asociada al usuario actual y a la película seleccionada
    lista = current_user.listums.find_by(pelicula: pelicula_id)
    if lista
      lista.destroy
      flash[:success] = "Película eliminada de la lista."
    else
      flash[:error] = "La película no estaba en la lista."
    end
  
    redirect_to lista_path
  end
  
  
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/views/todo/categoria.html.erb
<div class="container-sm text-center" style="margin-top:20px;"> 
    <div class="row" style="gap:20px;">
      <% if @error_message %>
        <p><%= @error_message %></p>
      <% else %>
        <% @movie_details.each do |pelicula| %>
          <div class="col">
            <div class="card" style="width: 18rem;height:40rem;">
              <img src="<%= @link_img + pelicula['poster_path'] %>" class="card-img-top" alt="">
              <div class="card-body">
                <h5 class="card-title"><%= pelicula['title'].upcase %></h5>
                <% @votos=pelicula['vote_average'].to_i.truncate / 2 %>
                <% (1..5).each do |i| %>
                <% if i <= @votos.to_i %>
                <i class="fa fa-star fa-lg"></i>
                <% end %>
              <% end %>
                <p class="card-text"><%= pelicula['vote_average'].truncate / 2%>/5</p>
                <div class="centrar" style="width: 100%;display:flex;justify-content:center;">
                  <%= link_to "Ver mas...", descripcion_path(parametro: pelicula['id']), class: 'btn btn-primary' %>
                </div> 
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div> 

    <!-- Paginación -->
    <nav aria-label="Page navigation example" style="margin-top: 30px;">
        <ul class="pagination justify-content-center">
          <% if @movie_details.current_page > 1 %>
            <li class="page-item">
              <%= link_to 'Previous', categoria_path(id_gen: params[:id_gen], page: @movie_details.current_page - 1), class: 'page-link' %>
            </li>
          <% end %>
          
          <% 1.upto(@movie_details.total_pages) do |page| %>
            <li class="page-item <%= 'active' if @movie_details.current_page == page %>">
              <%= link_to page, categoria_path(id_gen: params[:id_gen], page: page), class: 'page-link' %>
            </li>
          <% end %>
    
          <% if @movie_details.current_page < @movie_details.total_pages %>
            <li class="page-item">
              <%= link_to 'Next', categoria_path(id_gen: params[:id_gen], page: @movie_details.current_page + 1), class: 'page-link' %>
            </li>
          <% end %>
        </ul>
      </nav>

    

app/views/todo/descripcion.html.erb
<!-- Y así sucesivamente para el resto de la información -->

<div class="container" style="margin-top:20px;color:white;">
  <div class="clearfix">
    <img src="<%= @link_img + @info["poster_path"] %>" class="col-md-6 float-md-end mb-3 ms-md-3"  alt="Poster de la película">
    <h1><%= @info["title"] %></h1>


    <% if user_signed_in? %>
    <% if @esta_en_lista %>
      <%= form_tag({ controller: 'todo', action: 'enlistar' }, method: 'post') do %>
        <%= hidden_field_tag 'user_id', current_user.id %>
        <%= hidden_field_tag 'pelicula', @info['id'] %>
        <%= hidden_field_tag 'accion', 'quitar' %> <!-- Agregar campo para indicar que se va a quitar -->
        <%= submit_tag 'Quitar de la lista', class: "btn btn-danger" %>
      <% end %>
    <% else %>
      <%= form_tag({ controller: 'todo', action: 'enlistar' }, method: 'post') do %>
        <%= hidden_field_tag 'user_id', current_user.id %>
        <%= hidden_field_tag 'pelicula', @info['id'] %>
        <%= hidden_field_tag 'accion', 'enlistar' %> <!-- Agregar campo para indicar que se va a enlistar -->
        <%= submit_tag 'Enlistar Película', class: "btn btn-success" %>
      <% end %>
    <% end %>
  <% end %>
  


  <p><strong>Fecha de lanzamiento:</strong> <%= @info["release_date"] %></p>
  <p><strong>Popularidad:</strong><%= @info["popularity"]%></p>
  <p><strong>Descripción:</strong> <%= @info["overview"] %></p>



  <h2>Géneros</h2>
  <ul>
    <% @info["genres"].each do |genero| %>
      <li><%= genero["name"] %></li>
    <% end %>
  </ul>


  <h2>Compania</h2>
  <ul>
    <% @info["production_companies"].each do |companies| %>
      <li><%= companies["name"] %></li>
    <% end %>
  </ul>


  <% if @info_videos.is_a?(String) %>
    <% videos_data = JSON.parse(@info_videos) %>

    <% if videos_data.is_a?(Hash) && videos_data.has_key?("results") %>
      <% video_encontrado = false %>

      <% videos_data["results"].each do |video| %>

        <% if video["site"] == 'YouTube' && video["key"].present? && video["name"].downcase =~ /trailer/i %>
          <iframe width="480" height="320" src="https://www.youtube.com/embed/<%= video['key'] %>" frameborder="0" allowfullscreen></iframe>
          <% video_encontrado = true %>
          <% break %>
        <% end %>

      <% end %>

      <% unless video_encontrado %>
        <p>El video no está disponible en este momento. Puedes verlo en <a href="https://www.youtube.com/watch?v=<%= videos_data["results"].first['key'] %>">YouTube</a>.</p>
      <% end %>

    <% end %>

    
  <% end %>
  </div>
</div>

app/views/todo/homepage.html.erb
<h1>Hola mundo</h1>

app/views/todo/index.html.erb
<div class="container-sm" style="margin-top:20px;"> 
  <div class="row" style="gap:20px;">
    <% if @error_message %>
      <p><%= @error_message %></p>
    <% else %>
      <% @nuevas.each do |pelicula| %>
        <div class="col">
          <div class="card" style="width: 18rem;height:40rem;">
            <img src="<%= @link_img + pelicula['poster_path'] %>" class="card-img-top" alt="">
            <div class="card-body">
              <h5 class="card-title"><%= pelicula['title'].upcase %></h5>
              <% @votos=pelicula['vote_average'].to_i.truncate / 2 %>
              <% (1..5).each do |i| %>
              <% if i <= @votos.to_i %>

              <i class="fa fa-star fa-lg"></i>
              <% end %>
            <% end %>
              <p class="card-text"><%= pelicula['vote_average'].to_i.truncate / 2 %>/5</p>
              <p></p>
              <div class="centrar" style="width: 100%;display:flex;justify-content:center;">
                <%= link_to "Ver mas...", descripcion_path(parametro: pelicula['id']), class: 'btn btn-primary' %>
              </div> 
            </div>
          </div>
        </div>
      <% end %>
      <% if @nuevas.total_pages > 1 %>
        <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
            <% if @nuevas.current_page > 1 %>
              <li class="page-item">
                <%= link_to 'Previous', root_path(page: @nuevas.current_page - 1), class: 'page-link' %>
              </li>
            <% end %>
            <% 1.upto(@nuevas.total_pages) do |page| %>
              <li class="page-item <%= 'active' if @nuevas.current_page == page %>">
                <%= link_to page, root_path(page: page), class: 'page-link' %>
              </li>
            <% end %>
            <% if @nuevas.current_page < @nuevas.total_pages %>
              <li class="page-item">
                <%= link_to 'Next', root_path(page: @nuevas.current_page + 1), class: 'page-link' %>
              </li>
            <% end %>
          </ul>
        </nav>
      <% end %>
    <% end %>
  </div>
</div>

app/views/todo/lista.html.erb
<h1 style="color: white;">Listas:</h1>

<div class="container">
  <% @info.each do |movie_info| %>
    <div class="card mb-3" style="max-width: 80%;">
        <div class="row g-0">
        <div class="col-md-4" style="height: 300px; width: auto;">
            <img src="<%= @link_img + movie_info["poster_path"] %>" class="img-fluid rounded-start rounded" alt="Poster de la película" style="aspect-ratio: 2/3;">
        </div>
        <div class="col-md-8">
            <div class="card-body">
            <h1 class="card-title"><%= movie_info["title"] %></h1>
            <p class="card-text"><%= movie_info["overview"] %></p>
            <p class="card-text"><small class="text-body-secondary">Last updated 3 mins ago</small></p>
            
            <%= link_to "Eliminar de la lista", eliminar_pelicula_lista_path(movie_info["id"]), data: { turbo_method: :delete, turbo_confirm: 'Esta seguro?'}, class: "btn btn-danger" %>
            </div>
        </div>
        </div>
    </div>
    <% end %>
</div>

app/views/todo/populares.html.erb
<button type="button" class="btn btn-outline-primary">Primary</button>
<h1>Todo#homepage</h1>
<p>Find me in app/views/todo/homepage.html.erb</p>
<% @movie_details %>

<% if @error_message %>
  <p><%= @error_message %></p>
<% else %>
  <ul>
    <% @movie_details.each do |pelicula| %>
      <li>
        <img src="<%= @link_img + pelicula['poster_path'] %>" alt="">
        <strong><%= pelicula['title'].upcase %></strong>
        <p><%= pelicula['vote_average'].truncate %>/10</p>
        <%= link_to "Ver mas...", descripcion_path(parametro: pelicula['id']) %>

      </li>
    <% end %>
  </ul>
<% end %>

app/views/todo/prueba.html.erb
<!-- app/views/todo/prueba.html.erb -->

<h1>Top Películas Valoradas</h1>

<div class="row">
  <% @nuevas.each do |movie| %>
    <div class="col-md-4 mb-3">
      <div class="card">
        <img src="<%= @link_img + movie['poster_path'] %>" class="card-img-top" alt="<%= movie['title'] %>">
        <div class="card-body">
          <h5 class="card-title"><%= movie['title'] %></h5>
          <p class="card-text"><%= movie['overview'] %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<% if @nuevas.present? %>
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      <% if params[:page].to_i > 1 %>
        <li class="page-item"><%= link_to 'Previous', prueba_path(page: params[:page].to_i - 1), class: 'page-link' %></li>
      <% end %>
      
      <% (1..@nuevas.total_pages).each do |page| %>
        <li class="page-item <%= 'active' if params[:page].to_i == page %>">
          <%= link_to page, prueba_path(page: page), class: 'page-link' %>
        </li>
      <% end %>
      
      <% if @nuevas.size == 10 && params[:page].to_i < @nuevas.total_pages %>
        <li class="page-item"><%= link_to 'Next', prueba_path(page: params[:page].to_i + 1), class: 'page-link' %></li>
      <% end %>
    </ul>
  </nav>
<% end %>

app/views/todo/resultado.html.erb
<div class="container-sm text-center" style="margin-top:20px;"> 
  <div class="row" style="gap:20px;">
    <% if @error_message %>
      <p><%= @error_message %></p>
    <% else %>
      <% if @info.present? && @info.any? %>
        <% @info.each do |pelicula| %>

          <% if pelicula['poster_path'].present? %>
            <div class="col">
              <div class="card" style="width: 18rem;height:40rem;">
                <img src="<%= @link_img + pelicula['poster_path'] %>" class="card-img-top" alt="">
                <div class="card-body">
                  <% if pelicula['title'].present? %>
                    <h5 class="card-title"><%= pelicula['title'].upcase %></h5>
                  <% end %>
                  <% if pelicula['vote_average'].present? %>
                  <% @votos=pelicula['vote_average'].to_i.truncate / 2 %>
                  <% (1..5).each do |i| %>
                  <% if i <= @votos.to_i %>
      
                  <i class="fa fa-star fa-lg"></i>
                    <% end %>
                  <% end %>
                  <p class="card-text"><%= pelicula['vote_average'].to_i.truncate / 2 %>/5</p>
                  <% end %>
                  <div class="centrar" style="width: 100%;display:flex;justify-content:center;">
                    <% if pelicula['id'].present? %>
                      <%= link_to "Ver mas...", descripcion_path(parametro: pelicula['id']), class: 'btn btn-primary' %>
                    <% end %>
                  </div> 
                </div>
              </div>
            </div>
          <% end %>

          <div class="col">
            <div class="card" style="width: 18rem;height:40rem;">
              <% if pelicula['poster_path'].present? %>
                <img src="<%= @link_img + pelicula['poster_path'] %>" class="card-img-top" alt="">
              <% end %>
              <div class="card-body">
                <% if pelicula['title'].present? %>
                  <h5 class="card-title"><%= pelicula['title'].upcase %></h5>
                <% end %>
                <% if pelicula['vote_average'].present? %>
                  <p class="card-text"><%= pelicula['vote_average'].to_f.truncate %>/10</p>
                <% end %>
                <div class="centrar" style="width: 100%;display:flex;justify-content:center;">
                  <% if pelicula['id'].present? %>
                    <%= link_to "Ver mas...", descripcion_path(parametro: pelicula['id']), class: 'btn btn-primary' %>
                  <% end %>
                </div> 
              </div>
            </div>
          </div>

        <% end %>
      <% else %>
        <p>No se encontraron resultados</p>
      <% end %>
    <% end %>
  </div>
</div>